language: go
os:
  - linux
go:
  - go1.11
  - go1.12
  - go1.13
  - go1.14
go_import_path: github.com/novalagung/gubrak
env:
  - GO111MODULE=on
before_install:
  - go get github.com/mattn/goveralls
install:
  - go mod tidy
before_script:
  - wget http://downloads.majestic.com/majestic_million.csv
script:
  - go test -cover -race -v ./...
  - goveralls -service=travis-ci
