language: go

os:
  - linux

go:
  - "go1.8"
  - "go1.9"
  - "go1.10"

go_import_path: github.com/novalagung/gubrak

script:
  - cd test && go test -coverprofile=coverage.txt -covermode=atomic -race -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) -t "70c1f0d2-24bc-4612-9fee-a365a734ec05"
